// Fill out your copyright notice in the Description page of Project Settings.

#include "Projectile.h"
#include "GameFramework/ProjectileMovementComponent.h"
#include "Particles/ParticleSystemComponent.h"
#include "Components/StaticMeshComponent.h"
#include "PhysicsEngine/RadialForceComponent.h"

// Sets default values
AProjectile::AProjectile()
{
 	// Set this actor to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = false;

  CollisionMesh = CreateDefaultSubobject<UStaticMeshComponent>(FName("Collision Mesh"));
  SetRootComponent(CollisionMesh);
  CollisionMesh->SetNotifyRigidBodyCollision(true);
  CollisionMesh->SetVisibility(true);
  
  LaunchBlast = CreateDefaultSubobject<UParticleSystemComponent>(FName("Launch Blash"));
  LaunchBlast->AttachToComponent(RootComponent, FAttachmentTransformRules::KeepRelativeTransform);
  
  ImpactBlast = CreateDefaultSubobject<UParticleSystemComponent>(FName("Impact Blash"));
  ImpactBlast->AttachToComponent(RootComponent, FAttachmentTransformRules::KeepRelativeTransform);
  ImpactBlast->bAutoActivate = false;
  
  ProjectileMovement = CreateDefaultSubobject<UProjectileMovementComponent>(FName("Projectile Movement"));
  ProjectileMovement->bAutoActivate = false;
  
  ExplosionForce = CreateDefaultSubobject<URadialForceComponent>(FName("Explosion Force"));
  ExplosionForce->AttachToComponent(RootComponent, FAttachmentTransformRules::KeepRelativeTransform);
}

// Called when the game starts or when spawned
void AProjectile::BeginPlay()
{
	Super::BeginPlay();
  
//  CollisionMesh->
  CollisionMesh->OnComponentHit.AddDynamic(this, &AProjectile::OnHit);
}



void AProjectile::LaunchProjectile(float Speed)
{
  auto Time = GetWorld()->GetTimeSeconds();
//  UE_LOG(LogTemp, Warning, TEXT("%f: Projectile launched at %f"), Time, Speed)
  
  ProjectileMovement->SetVelocityInLocalSpace(FVector::ForwardVector * Speed);
  ProjectileMovement->Activate();
}

void AProjectile::OnHit(UPrimitiveComponent* HitComponent, AActor* OtherActor, UPrimitiveComponent* OtherComponent, FVector NormalImpulse, const FHitResult& Hit)
{
  LaunchBlast->Deactivate();
  ImpactBlast->Activate();
  ExplosionForce->FireImpulse();
  
  SetRootComponent(ImpactBlast);
  CollisionMesh->DestroyComponent();
}

